sources:      
############################# Production Sources #################################
  - name: input_data
    description: pipeml input data
    database: db
    schema: source
    tables:
      - name: input_data

