version: '3.8'

networks:
  pipenetwork:
    driver: bridge

services:

  spark:
    build: ./spark-server
    container_name: spark-server
    hostname: spark-server
    stdin_open: true
    tty: true
    volumes:
      - spark-volume:/spark-warehouse
    networks:
      - pipenetwork
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
      - "18080:18080"
      - "10000:10000"
      - "9083:9083"
    command: ["/entrypoint_master.sh"]
  
  spark_worker:
    build: ./spark-server
    container_name: spark-wroker
    hostname: spark-worker
    stdin_open: true
    tty: true
    volumes:
      - spark-volume:/spark-warehouse
    depends_on:
      - spark
    networks:
      - pipenetwork
    command: ["/entrypoint_worker.sh"]

  postgres:
    build: ./postgres-server
    container_name: postgres-server
    user: root
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    
    ports:
      - "5432:5432"
    
    volumes:
      - pipedata:/var/lib/postgresql/data
    
    networks:
      - pipenetwork

  transformation:
    build: ./transformation
    container_name: transformation
    stdin_open: true
    tty: true
    volumes:
      - ./transformation:/app
    working_dir: /app
    
    networks:
      - pipenetwork
    
    depends_on:
      - spark
      - spark_worker

  ml:
    build: ./ml
    container_name: ml
    stdin_open: true
    tty: true
    volumes:
      - ./ml:/app/
    working_dir: /app
    networks:
      - pipenetwork

volumes:
  pipedata:
  spark-volume:
