services:

  transformation:
    build: ./transformation
    container_name: transformation
    stdin_open: true
    tty: true
    volumes:
      - ./transformation:/app
      - input-data-volume:/app/datasets
      - duck-db-data:/app/database
    working_dir: /app
    networks:
      - pipenetwork    

  ml:
    build: ./ml
    container_name: ml
    stdin_open: true
    tty: true
    volumes:
      - ./ml:/app/
      - duck-db-data:/app/database
    working_dir: /app
    ports:
      - "6969:6969"
    networks:
      - pipenetwork


networks: #would be useful in future for inter container communication
  pipenetwork:
    driver: bridge 

volumes:
  pipedata:
    driver: local
  input-data-volume:
    driver: local
  duck-db-data:
    driver: local