pipeml:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres-server 
      user: user
      password: password
      port: 5432
      dbname: db
      schema: public
      threads: 4
